### ISSUE TITLE
Readme.md 내용 작성

### ISSUE THREAD

**Issue by ChickenRushKR** [tjalsrb97/Project2#1]
작성 형식:
제목: Assignment2
팀장
학번 이름 아이디
팀원
학번 이름 아이디 ...
**형식으로 코멘트 바랍니다.**

**Comment by ChickenRushKR** [comment]
2016722036 김현진 ChickenRushKR

**Comment by tjalsrb97** [comment]
2016722066 서민규 tjalsrb97

**Comment by ubinjin** [comment]
2016722084 진우빈 ubinjin

**Comment by KYankee6** [comment]
2016722011 양준혁 @KYankee6
