### ISSUE TITLE
함수 7 코드 작성

### ISSUE THREAD

**Issue by KYankee6** [tjalsrb97/Project2#14]
함수 7을 구현할때, `localtime()` 이용하여 시간 구조체(`tm*`) 포인터를 넘겨주는데 이를 모두 초로 바꿔서 코드를 작성하기에 조금 불편합니다. 
특히 월(`tm->tm_month`)를 바꾸려면 이를 모두 바꾸려면 1~5월 날을 모두 구해야하고, 이러면 윤년인지 아닌지도 계산해야하는데 좋은 멤버변수가 없을까요?

**Comment by ubinjin** [comment]
yday를 사용하면 될겁니당

**Comment by tjalsrb97** [comment]
강의자료를 확인하세요

**Comment by KYankee6** [comment]
@ubinjin `tm*`의 멤버변수인가요?

**Comment by ubinjin** [comment]
@KYankee6 넵 맞습니당
