### ISSUE TITLE
함수 6 기반 기술 조사

### ISSUE THREAD

**Issue by ubinjin** [tjalsrb97/Project2#17]
stat 구조체 내부의 st_blocks 변수가 블록의 개수를 의미한다고 하는데 한 블록 당 사이즈는 고정인가요?

**Comment by tjalsrb97** [comment]
시스템 프로그래밍 시간에 배웠는데, 512B로 고정으로 알고 있습니다!

**Comment by KYankee6** [comment]
`stat`은 구조체가 아니라 시스템콜인것 같습니다.

> https://linux.die.net/man/2/stat

확인해보세욥

**Comment by ubinjin** [comment]
@tjalsrb97 앗 감사합니당!

**Comment by ChickenRushKR** [comment]
512MB인것같습니다!

**Comment by ubinjin** [comment]
@KYankee6 이미 해결됐습니다
