### ISSUE TITLE
함수 8 기술 조사

### ISSUE THREAD

**Issue by KYankee6** [tjalsrb97/Project2#18]
함수 8은 함수 7과 같이 `localtime()`함수를 사용하겠습니다.
자세한 내용은 아래 링크를 확인해주세요.

> https://linux.die.net/man/3/localtime

**Comment by tjalsrb97** [comment]
넵넵 확인했습니다.

**Comment by ChickenRushKR** [comment]
> 하지 말아야 할 것을 효율적으로 하는 것 보다 더 비생산적인 것은 없다 - 피터 드러커


고생하셨습니다.
