### ISSUE TITLE
함수 8 코드 작성

### ISSUE THREAD

**Issue by KYankee6** [tjalsrb97/Project2#19]
함수 8 코드 작성도 localtime()의 반환값과 `tm` 구조체 포인터를 이용하여 진행합니다.

**Comment by KYankee6** [comment]
#

1. `tm`의 멤버변수 시간, 분을 받아오기
2.  받아온 시간, 분을 모두 분으로 바꾸기
3. 이후 `result1`, `result2`변수에 받아온 시간을 합치기
4. 비교하여 어떤것이 먼저만든 파일인지 확인

**Comment by KYankee6** [comment]
코드를 작성하는데 자꾸 이상한 오류가 발생합니다.
제 코드의 일부분입니다.
```
time1 = localtime(&stat1.st_mtime);
time2 = localtime(&stat2.st_mtime);

tm_hour1 = (time1->tm_hour) * 60;
tm_min1 = time1->tm_min;

tm_hour2 = (time2->tm_hour) * 60;
tm_min2 = time2->tm_min;

result1 = tm_hour1 + tm_min1;
result2 = tm_hour2 + tm_min2;
```
`printf`함수로 확인해본 결과 result1과 result2가 같은 값을 가지고 있는것으로 보입니다.

**Comment by ubinjin** [comment]
localtime() 재선언하니까 되더라구요

**Comment by ChickenRushKR** [comment]
> 코드를 작성하는데 자꾸 이상한 오류가 발생합니다.
> 제 코드의 일부분입니다.
> 
> ```
> time1 = localtime(&stat1.st_mtime);
> time2 = localtime(&stat2.st_mtime);
> 
> tm_hour1 = (time1->tm_hour) * 60;
> tm_min1 = time1->tm_min;
> 
> tm_hour2 = (time2->tm_hour) * 60;
> tm_min2 = time2->tm_min;
> 
> result1 = tm_hour1 + tm_min1;
> result2 = tm_hour2 + tm_min2;
> ```
> 
> `printf`함수로 확인해본 결과 result1과 result2가 같은 값을 가지고 있는것으로 보입니다.

저도 실험해본 결과 같게 됩니다.. 주소값이 똑같이 나오는데 해결하신분 계신가요?

**Comment by KYankee6** [comment]
`localtime()` 함수가 local static 변수에 저장한다고 하는데요..

> https://linux.die.net/man/3/localtime

> The localtime() function converts the calendar time timep to broken-down time representation, expressed relative to the user's specified timezone. The function acts as if it called tzset(3) and sets the external variables tzname with information about the current timezone, timezone with the difference between Coordinated Universal Time (UTC) and local standard time in seconds, and daylight to a nonzero value if daylight savings time rules apply during some part of the year. The return value points to a statically allocated struct which might be overwritten by subsequent calls to any of the date and time functions. The localtime_r() function does the same, but stores the data in a user-supplied struct. It need not set tzname, timezone, and daylight.

조금 헷갈리긴 하지만 locate_r()함수를 사용하여 고쳐보도록 하겠습니다

**Comment by ubinjin** [comment]
고치셨나요?

**Comment by KYankee6** [comment]
혹시 전역변수 `struct tm* time1, *time2`를 포인터가아니라 그냥 인스턴스로 바꾸면 안되나요?
규정에 어긋난다면 `locate_r()` 프로토타입과 맞지 않아서 쓸수 없습니다.

**Comment by ChickenRushKR** [comment]
> 혹시 전역변수 `struct tm* time1, *time2`를 포인터가아니라 그냥 인스턴스로 바꾸면 안되나요?
> 규정에 어긋난다면 `locate_r()` 프로토타입과 맞지 않아서 쓸수 없습니다.

스켈레톤 코드를 크게 변형하지 않기 때문에
아마 문제는 없을 것 같습니다.

**Comment by ubinjin** [comment]
> > 혹시 전역변수 `struct tm* time1, *time2`를 포인터가아니라 그냥 인스턴스로 바꾸면 안되나요?
> > 규정에 어긋난다면 `locate_r()` 프로토타입과 맞지 않아서 쓸수 없습니다.
> 
> 스켈레톤 코드를 크게 변형하지 않기 때문에
> 아마 문제는 없을 것 같습니다.

요구사항에 정해진 코드 양식을 따랐는가에 대한 평가 기준 사항이 있는데
변형하는 것 자체가 그 기준에 어긋나는 것 아닐까요? 변형은 하면 안 된다고 생각합니다

**Comment by ChickenRushKR** [comment]
> > > 혹시 전역변수 `struct tm* time1, *time2`를 포인터가아니라 그냥 인스턴스로 바꾸면 안되나요?
> > > 규정에 어긋난다면 `locate_r()` 프로토타입과 맞지 않아서 쓸수 없습니다.
> > 
> > 
> > 스켈레톤 코드를 크게 변형하지 않기 때문에
> > 아마 문제는 없을 것 같습니다.
> 
> 요구사항에 정해진 코드 양식을 따랐는가에 대한 평가 기준 사항이 있는데
> 변형하는 것 자체가 그 기준에 어긋나는 것 아닐까요? 변형은 하면 안 된다고 생각합니다

그건 잘 모르겠는데요 혹시 조교님께 연락하시는건 어때요?
`micky1996@naver.com`입니다

**Comment by KYankee6** [comment]
> > > 혹시 전역변수 `struct tm* time1, *time2`를 포인터가아니라 그냥 인스턴스로 바꾸면 안되나요?
> > > 규정에 어긋난다면 `locate_r()` 프로토타입과 맞지 않아서 쓸수 없습니다.
> > 
> > 
> > 스켈레톤 코드를 크게 변형하지 않기 때문에
> > 아마 문제는 없을 것 같습니다.
> 
> 요구사항에 정해진 코드 양식을 따랐는가에 대한 평가 기준 사항이 있는데
> 변형하는 것 자체가 그 기준에 어긋나는 것 아닐까요? 변형은 하면 안 된다고 생각합니다

알겠습니다. Quotes 가 너무많아 어지럽네요. 스켈레톤 코드 양식에 맞춰 진행하도록 하겠습니다.

**Comment by KYankee6** [comment]
@ChickenRushKR  감사합니다. 연락드리겠습니다.

**Comment by KYankee6** [comment]
확인해보니 
```
time1 = localtime(&stat1.st_mtime);
time2 = localtime(&stat2.st_mtime);
```
변수 선언 순서를 copy할 수 있도록 순서를 바꾸거나
time1 변수를 동적할당하면 해결된다고 합니다.
