### ISSUE TITLE
Wiki 페이지 작성

### ISSUE THREAD

**Issue by ChickenRushKR** [tjalsrb97/Project2#2]
GitHub페이지 소개에는 "광운대학교 컴퓨터정보공학부 소프트웨어공학 수업 프로젝트 2를 위한 Github 페이지입니다."
팀명 PRO4S, 팀원 서민규 김현진 진우빈 양준혁

이렇게 달아도 될까요?

**Comment by ubinjin** [comment]
서민규 양준혁 김현진 진우빈 순으로 해주세요 참고로 학번순입니다.

**Comment by KYankee6** [comment]
@ChickenRushKR 넵

**Comment by tjalsrb97** [comment]
네 좋습니다!

**Comment by ubinjin** [comment]
로드 맵도 추가해주세용

**Comment by ChickenRushKR** [comment]
> 로드 맵도 추가해주세용

내용 추가해서 wiki page에 올렸습니다. 감사합니다.
