### ISSUE TITLE
함수 7 기술 조사

### ISSUE THREAD

**Issue by KYankee6** [tjalsrb97/Project2#6]
함수 7은 함수 1,2에서 사용하는 localtime() 함수를 사용해서 진행할 예정입니다.
함수 프로토타입은 다음과 같습니다 
struct tm *localtime(const time_t *timep);
자세한 내용은 아래 링크를 확인해주세요.
https://linux.die.net/man/3/localtime

**Comment by tjalsrb97** [comment]
확인했는데 localtime을 활용하는게 좋을 것 같네요
